steps:
  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.3.0:
        files:
          - hooks/**
          - scripts/**

  - label: ":rocket: Test"
    plugins:
      docker-compose#v4.16.0:
        run: tests
        cli-version: 2

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v3.2.0:
        id: a-github-user/template